### PR TITLE
Add script to run linters locally (ROS2)

### PR DESCRIPTION
**Pull request by ojasjoshi**
*Issue #, if available:*

*Description of changes:*
Add script to run linters locally (ROS2)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mm318** [comment]
How come there is a linting failure in this pull request?

**Comment by ojasjoshi** [comment]
> How come there is a linting failure in this pull request?

I can't figure out either. The [previous PR linter workflow did check for route_manager.py](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/runs/1660068591]) and passed. No updates to route_manager.py since last linter commit. Weird!

**Comment by mm318** [comment]
It just came across my mind that users should lint via `colcon test`. The `ament` linters should be specified in the `package.xml` and installed via `rosdep`. (Though this approach might not work for ROS1 packages.)

**Comment by mm318** [comment]
> > How come there is a linting failure in this pull request?
> 
> I can't figure out either. The [previous PR linter workflow did check for route_manager.py](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/runs/1660068591%5D) and passed. No updates to route_manager.py since last linter commit. Weird!

Maybe there was an update to the linter.

**Pull request closed without merging**
